#!/usr/bin/env bash
#Transfers file from client to server
if [ "$#" -lt 4 ];
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_T0_SSH_KEY";
else
  scp -o StrictHostkeyChecking=no -i "$4" "$1" "$3@$2":~/;
fi
