#!/usr/bin/env bash
#created a redirection page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80;
    server_name your_domain.com www.your_domain.com;

    return 301 https://your_new_domain.com\$request_uri;
}" > /etc/nginx/sites-enlabled/default

sudo service nginx restart
