#!/usr/bin/env bash
#install haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

sudo echo "
frontend airbnb
	bind *:80
    mode http
	default_backend myservers

backend myservers
	balance roundrobin
	server web-01 100.26.173.80:80 check
	server web-02 100.25.193.241:80 check
" >> sudo /etc/haproxy/haproxy.cfg
sudo echo "
ubuntu 100.26.173.80 397593-web-01
ubuntu 100.25.193.241 397593-web-02
" >> sudo /etc/hosts
sudo service haproxy start
