#!/usr/bin/env bash
#make sure nginx listens to port 80
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
