#!/usr/bin/env bash
# A script that prints Best school 10 times and Hi on the 9th line
counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
#	((counter++))
		if [ $counter -eq 9 ]
		then
			echo "Hi"
		fi
	((counter++))
done
